In [27]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import PolynomialFeatures

In [39]:
df=pd.read_csv('StudentPerformanceFactors.csv')
df.head(4)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71

In [40]:
df.drop(columns=['Extracurricular_Activities','Internet_Access','Teacher_Quality','Parental_Education_Level','Distance_from_Home'],inplace=True)
df.head(4)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Gender,Exam_Score
0,23,84,Low,High,7,73,Low,0,Low,Public,Positive,3,No,Male,67
1,19,64,Low,Medium,8,59,Low,2,Medium,Public,Negative,4,No,Female,61
2,24,98,Medium,Medium,7,91,Medium,2,Medium,Public,Neutral,4,No,Male,74
3,29,89,Low,Medium,8,98,Medium,1,Medium,Public,Negative,4,No,Male,71

In [41]:
cols = ['Parental_Involvement','Access_to_Resources','Motivation_Level','Family_Income','School_Type','Peer_Influence']


encoder1=OrdinalEncoder()
df[cols]=encoder1.fit_transform(df[cols])


encoder2 = OneHotEncoder(sparse_output=False)

encoded= encoder2.fit_transform(df[['Gender','Learning_Disabilities']])

encoded_df = pd.DataFrame(
    encoded,# has the encoded data stored
    columns=encoder2.get_feature_names_out(['Gender','Learning_Disabilities'])  # this will takes out columns names from cols
)
df = df.drop(columns=['Gender','Learning_Disabilities'])# will drop the original columns in df datset

df = pd.concat([df, encoded_df], axis=1)  # merging orginal datset with encoded data 

df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,School_Type,Peer_Influence,Physical_Activity,Exam_Score,Gender_Female,Gender_Male,Learning_Disabilities_No,Learning_Disabilities_Yes
0,23,84,1.0,0.0,7,73,1.0,0,1.0,1.0,2.0,3,67,0.0,1.0,1.0,0.0
1,19,64,1.0,2.0,8,59,1.0,2,2.0,1.0,0.0,4,61,1.0,0.0,1.0,0.0
2,24,98,2.0,2.0,7,91,2.0,2,2.0,1.0,1.0,4,74,0.0,1.0,1.0,0.0
3,29,89,1.0,2.0,8,98,2.0,1,2.0,1.0,0.0,4,71,0.0,1.0,1.0,0.0
4,19,92,2.0,2.0,6,65,2.0,3,2.0,1.0,1.0,4,70,1.0,0.0,1.0,0.0

In [28]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Learning_Disabilities',
       'Gender', 'Exam_Score', 'Gender_Female', 'Gender_Male',
       'Learning_Disabilities_No', 'Learning_Disabilities_Yes'],
      dtype='str')

In [ ]:
x=df.drop(columns=['Exam_Score'])
y=df['Exam_Score']
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)  # Enabling the interaction term
X_new = poly.fit_transform(x)
model1=LinearRegression()
model1.fit(X_new,y)
y_pred=model1.predict(X_new)
print("Mean Squared Error:",mean_squared_error(y,y_pred))
print("R2 Score:",r2_score(y,y_pred))

Mean Squared Error: 5.485725127638169
R2 Score: 0.6375076771891763

In [47]:
# without Interaction term
model2=LinearRegression()
model2.fit(x,y)
y_pred=model2.predict(x)
print("Mean Squared Error:",mean_squared_error(y,y_pred))
print("R2 Score:",r2_score(y,y_pred))

Mean Squared Error: 5.563858924494435
R2 Score: 0.6323446584717856

In [ ]:
# Without interaction term,the model has a higher MSE and a Lower R2 score,indicating that the model with interaction term perform better in capturing the relationship between feature and target variable.