In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
df=pd.read_csv("C:\\Users\\mukes\\OneDrive\\Documents\\ML\\ipl data set.csv")

df.head()

,match_id,batting_team,bowling_team,venue,pitch_type,pitch_condition,current_score,overs_completed,wickets_out,runs_last_5_overs,overs_remaining,wickets_remaining,run_rate,season,final_score
0,1,CSK,RCB,Rajiv Gandhi Stadium,Balanced,Dry,133,12,5,68,8,5,11.08,2024,229
1,2,SRH,DC,Rajiv Gandhi Stadium,Batting Friendly,Dry,76,16,3,55,4,7,4.75,2012,119
2,3,SRH,PBKS,Rajiv Gandhi Stadium,Balanced,Green,126,13,6,32,7,4,9.69,2017,195
3,4,PBKS,RR,Wankhede Stadium,Batting Friendly,Dusty,65,13,0,48,7,10,5.00,2018,122
4,5,PBKS,GT,Sawai Mansingh Stadium,Bowling Friendly,Green,32,5,4,57,15,6,6.40,2020,115

In [7]:
encoder2=OneHotEncoder(sparse_output=False)
converted_data=encoder2.fit_transform(df[['batting_team','bowling_team','venue']])

column_names=encoder2.get_feature_names_out(['batting_team','bowling_team','venue'])
converted_data_df=pd.DataFrame(converted_data,columns=column_names)

x=df.drop(['batting_team','bowling_team','venue'],axis=1)

x=pd.concat([x.reset_index(drop=True),converted_data_df.reset_index(drop=True)],axis=1)
x.head()
''' 

sparse_output=False → output will be a normal NumPy array, not a sparse matrix




fit ->
Learns all unique categories:
batting_team → all teams
bowling_team → all teams
venue → all stadiums
🔸 transform
Converts them into one-hot encoded columns (0/1)

when we convert the columns next time i.e. when we take input from user and then we need to convert them to back to encoded data then at that second time
we don't need to fit the encoder again because we have already fiited it on the whole data and we have already learned all the unique categories 
we then just need to transform the user input using the same encoder not different encoder because if we use different encoder then it will learn 
the categories again and it will not be same as the one we have already learned.


column_names = encoder2.get_feature_names_out(['batting_team','bowling_team','venue'])
👉 Generates names for new columns like:

batting_team_India
batting_team_Australia
bowling_team_India
bowling_team_Australia
venue_Mumbai
venue_Delhi




converted_data_df = pd.DataFrame(converted_data, columns=column_names)

👉 From pandas

Turns the encoded array into a DataFrame
Assigns proper column names

✔ Now data looks structured instead of raw matrix




x = df.drop(['batting_team','bowling_team','venue'], axis=1)

👉 Removes original categorical columns

✔ Why:

You don’t want both:
original text columns ❌
encoded columns ✔





x = df.drop(['batting_team','bowling_team','venue'], axis=1)

👉 Removes original categorical columns

✔ Why:

You don’t want both:
original text columns ❌
encoded columns ✔
 0 data joining with Row 5 ❌
...



 '''

,match_id,pitch_type,pitch_condition,current_score,overs_completed,wickets_out,runs_last_5_overs,overs_remaining,wickets_remaining,run_rate,...,bowling_team_RR,bowling_team_SRH,venue_Arun Jaitley Stadium,venue_Chepauk Stadium,venue_Chinnaswamy Stadium,venue_Eden Gardens,venue_Narendra Modi Stadium,venue_Rajiv Gandhi Stadium,venue_Sawai Mansingh Stadium,venue_Wankhede Stadium
0,1,Balanced,Dry,133,12,5,68,8,5,11.08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2,Batting Friendly,Dry,76,16,3,55,4,7,4.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,Balanced,Green,126,13,6,32,7,4,9.69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,4,Batting Friendly,Dusty,65,13,0,48,7,10,5.00,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,Bowling Friendly,Green,32,5,4,57,15,6,6.40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0