In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv("C:\\Users\\mukes\\OneDrive\\Documents\\ML\\ipl data set.csv")
df.head()

,match_id,batting_team,bowling_team,venue,pitch_type,pitch_condition,current_score,overs_completed,wickets_out,runs_last_5_overs,overs_remaining,wickets_remaining,run_rate,season,final_score
0,1,CSK,RCB,Rajiv Gandhi Stadium,Balanced,Dry,133,12,5,68,8,5,11.08,2024,229
1,2,SRH,DC,Rajiv Gandhi Stadium,Batting Friendly,Dry,76,16,3,55,4,7,4.75,2012,119
2,3,SRH,PBKS,Rajiv Gandhi Stadium,Balanced,Green,126,13,6,32,7,4,9.69,2017,195
3,4,PBKS,RR,Wankhede Stadium,Batting Friendly,Dusty,65,13,0,48,7,10,5.00,2018,122
4,5,PBKS,GT,Sawai Mansingh Stadium,Bowling Friendly,Green,32,5,4,57,15,6,6.40,2020,115

In [ ]:
encoder1=OrdinalEncoder()
df['pitch_condition']=encoder1.fit_transform(df[['pitch_condition']])
df.head()
'''   

IN OneHotEncoding we input one column and output is multiple columns of that one column so we have to create a new dataframe for those multiple columns and deleting the original columns from dataset
but in ordinal encoding input of one column gives output of only one columns so no need to create a new dataframe just replace it with original column.

'''

,match_id,batting_team,bowling_team,venue,pitch_type,pitch_condition,current_score,overs_completed,wickets_out,runs_last_5_overs,overs_remaining,wickets_remaining,run_rate,season,final_score
0,1,CSK,RCB,Rajiv Gandhi Stadium,Balanced,0.0,133,12,5,68,8,5,11.08,2024,229
1,2,SRH,DC,Rajiv Gandhi Stadium,Batting Friendly,0.0,76,16,3,55,4,7,4.75,2012,119
2,3,SRH,PBKS,Rajiv Gandhi Stadium,Balanced,3.0,126,13,6,32,7,4,9.69,2017,195
3,4,PBKS,RR,Wankhede Stadium,Batting Friendly,1.0,65,13,0,48,7,10,5.00,2018,122
4,5,PBKS,GT,Sawai Mansingh Stadium,Bowling Friendly,3.0,32,5,4,57,15,6,6.40,2020,115